#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Check if a merge is in progress
if git rev-parse -q --verify MERGE_HEAD > /dev/null 2>&1; then
  echo "A merge is currently in progress."
else
  echo "--- Pulling latest commit ---"
  git pull
fi

# Type check the project before commit
npx tsc --noEmit